version: '3'
services:
    pg:
        image: postgres:14.0-bullseye
        environment:
            POSTGRES_PASSWORD: "root"
            POSTGRES_DB: "foodbear"
        ports:
            - "127.0.0.1:5432:5432"


