version: '3'
services:
    pg:
        image: postgres:14.0-bullseye
        environment:
            POSTGRES_PASSWORD: "root"
            POSTGRES_DB: "foodbear"
        ports:
            - "127.0.0.1:5432:5432"

    api:
        ports:
            - "127.0.0.1:8080:8080"
        build:
            context: .
            args:
                PROJECT-NAME: food-bear
        entrypoint: "java -jar food-bear-0.0.1-SNAPSHOT.jar"



