version: '3'
services:
    pg:
        image: postgres:14.0-bullseye
        environment:
            POSTGRES_PASSWORD: "root"
            POSTGRES_DB: "foodbear"
        ports:
            - "127.0.0.1:5432:5432"

    api:
        ports:
            - "127.0.0.1:8081:8080"
        build:
            context: .
            args:
                PROJECT-NAME: food-bear
        entrypoint: "java -jar food-bear-docker.jar"

    activemq:
        image: symptoma/activemq:latest
        container_name: activemqdocker
        ports:
            - "127.0.0.1:61616:61616"
            - "127.0.0.1:8161:8161"
        environment:
            ACTIVEMQ_ADMIN_LOGIN: "admin"
            ACTIVEMQ_ADMIN_PASSWORD: "admin"
            ACTIVEMQ_STATIC_QUEUES: "foodbear-queue"



