server:
  servlet:
    context-path: "/api"

spring:
  datasource:
    url: jdbc:postgresql://pg:5432/foodbear
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  main:
    allow-bean-definition-overriding: true
  activemq:
    broker-url: tcp://activemq:61616
  config:
    activate:
      on-profile:

jwt:
  secret: 092345i6wetrp09wpOOPUl

liquibase:
  change-log: classpath:liquibase-changeLog.yaml




